### ISSUE TITLE
Update to v 0.6.2

### ISSUE THREAD

**Issue by palmjack** [chops318/bulma-scss-version#2]
Any chance you could update to v 0.6.2?
Thanks so much for the scss version since I hate saas syntax

**Comment by chops318** [comment]
Sure thing, I'll do that some time today when I get a moment, thanks for alerting me. That is exactly why I made this, don't like sass syntax either.

**Comment by chops318** [comment]
@palmjack 
updated it, if you would test it and confirm any changes are correct i'll close this. thanks for helping out! (sorry I took so long and can't test it, super busy)
