### ISSUE TITLE
Latest Version Broken

### ISSUE THREAD

**Issue by bduff9** [chops318/bulma-scss-version#3]
Looks like when you converted to SCSS, you forgot to change the file imports as they still point to the sass folder and sass files, so the compile of bulma.scss therefore fails.  I can manually change my instance, but any chance you can fix this for my other deployments?  Thanks!

**Comment by chops318** [comment]
Just published the pull request by @tommydunn , thanks for pointing this out!

**Comment by bduff9** [comment]
Hey, just for future reference, you might want to test the change or at least wait until it is tested to close the issue.  This is still not resolved, however I will just fix it myself.

**Comment by chops318** [comment]
Ah, yeah that definitely would've helped, thanks for helping out. I'll be updating this to cover 0.7.1 this weekend (tested)
