### ISSUE TITLE
Npmjs package still broken

### ISSUE THREAD

**Issue by agungkes** [chops318/bulma-scss-version#6]
Looks like the package that is in npmjs is still not correct, still an error on the path you imported. Is there any chance to fix this ? Thanks

**Comment by chops318** [comment]
Hi, sorry for the delayed response, I just published version 1.4.0, this should fix any issues, but let me know if there are still problems. I will close this issue when you report back. I would test, but I really can't prioritize that until the weekend. Thanks for the help @cintarembo and if you have a fix ready, please submit a PR and I will gladly merge.
